name: NoctGram
options:
  deploymentTarget:
    iOS: '15.0'
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: '5.0'
    MARKETING_VERSION: '1.1.1'
    CURRENT_PROJECT_VERSION: '1'
    IPHONEOS_DEPLOYMENT_TARGET: '15.0'
    ENABLE_USER_SCRIPT_SANDBOXING: YES
targets:
  NoctGram:
    type: application
    platform: iOS
    sources:
      - path: NoctGram
        excludes: [Info.plist]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.noctgram.ios
        INFOPLIST_FILE: NoctGram/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGN_STYLE: Manual
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: '1,2'
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        ENABLE_BITCODE: NO
  NoctGramTests:
    type: bundle.unit-test
    platform: iOS
    sources: [NoctGramTests]
    dependencies:
      - target: NoctGram
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.noctgram.ios.tests
  NoctGramUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [NoctGramUITests]
    dependencies:
      - target: NoctGram
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.noctgram.ios.uitests
schemes:
  NoctGram:
    build:
      targets:
        NoctGram: all
    run:
      config: Debug
    archive:
      config: Release
    test:
      targets: [NoctGramTests, NoctGramUITests]
